spring:
  main:
    banner-mode: off
  application:
    name: shows-data-service
  datasource:
    url: ${POSTGRES_JDBC_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 1
      auto-commit: false
  jpa:
    show-sql: ${SHOW_SQL:false}
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.default_schema: shows
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

springdoc:
  paths-to-match:
    - /api/shows/**
  swagger-ui:
    path: /api/swagger-ui
    url: /api/v3/api-docs
  api-docs:
    path: /api/v3/api-docs

server:
  port: 8080
  error:
    whitelabel:
      enabled: false

keycloak:
  auth-server-url: http://localhost:8484/auth
  realm: my_realm
  resource: my_client
  public-client: true
  bearer-only: true