server:
  port: ${SERVER_PORT:8081}
spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  data:
    rest:
      base-path: /front

keycloak:
  auth-server-url: ${KEYCLOAK_URL:http://localhost:8484/auth}
  realm: my_realm
  resource: my_client
  public-client: true