server:
  port: 8081
spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true

keycloak:
  auth-server-url: http://localhost:8484/auth
  realm: my_realm
  resource: my_client
  public-client: true