management:
  endpoints:
    web:
      exposure:
        include: health, loggers, metrics, configprops
  health:
    db:
      enabled: true
    diskspace:
      enabled: true
  endpoint:
    health:
      show-details: always